name: AutoUpdate

on:
  schedule:
    - cron: '0 8 * * *'

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update
      run: ./build.ps1 -t autoupdate