name: CD

on:
  workflow_dispatch:
    inputs:
      pkg:
        description: 'Upload packages'
        required: false
        default: "false"
      image:
        description: 'Upload images'
        required: false
        default: "false"

defaults:
  run:
    shell: pwsh

env:
  dotnet-version: "5.0.x"
  node-version: "12.x"
  build_version: "0.0.2-preview.${{ github.run_number }}"

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: Build and Deploy packages
      run: Invoke-psake cd
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./packages
    - name: Upload to Azure packages
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZ_TOKEN }}
      run: Invoke-psake publish-packages
    - name: Upload to NuGet
      if: ${{ github.event.inputs.pkg == 'true' }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: Invoke-psake publish-packages-release